version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  discord_bot:
    build: .
    command: python discord_bot/main.py
    volumes:
      - .:/app
    depends_on:
      - app