blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yourusername/mcp-dm-gemini/discussions
    about: Ask questions, share ideas, or discuss the project with the community
  - name: 🔒 Security Issue
    url: https://github.com/yourusername/mcp-dm-gemini/security/advisories/new
    about: Report a security vulnerability (private disclosure)
  - name: 📖 Documentation
    url: https://github.com/yourusername/mcp-dm-gemini/blob/main/docs/
    about: Check the documentation for setup and usage guides