name: Feature Request
description: Suggest an idea for TTRPG Assistant
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🎲✨

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm frustrated when... / I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I think the solution should work like...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I've also considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - PDF Processing
        - Search Engine
        - MCP Server
        - Web UI
        - Discord Bot
        - Character Generation
        - NPC Generation
        - Map Generation
        - Session Management
        - Content Packs
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - I'm not sure
    validations:
      required: false

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        For example:
        1. User opens the web UI
        2. User clicks "Advanced Search"
        3. User selects filters for spell level and school
        4. System returns filtered results

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please check all that apply
      options:
        - label: This feature would benefit multiple users, not just my specific use case
        - label: I would be willing to help test this feature
        - label: I would be willing to help implement this feature (if I have the skills)
        - label: This feature is compatible with the project's scope and goals

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true