# config.yaml
chromadb:
  persist_directory: "./chroma_db"

embedding:
  model: "all-MiniLM-L6-v2"
  batch_size: 32
  cache_embeddings: true

pdf_processing:
  max_file_size_mb: 100
  ocr_enabled: true
  preserve_formatting: true
  # Adaptive PDF processing settings
  enable_adaptive_learning: true
  pattern_cache_dir: "./pattern_cache"
  min_pattern_frequency: 3
  min_pattern_confidence: 0.6

search:
  default_max_results: 5
  similarity_threshold: 0.7
  enable_keyword_fallback: true

mcp:
  server_name: "ttrpg-assistant"
  version: "1.0.0"

discord:
  token: "YOUR_DISCORD_BOT_TOKEN"